apiVersion: v1
kind: Namespace
metadata:
  name: octopusdemo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myoctopusapp
  namespace: octopusdemo
  labels:
    app: myoctopusapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myoctopusapp
  template:
    metadata:
      labels:
        app: myoctopusapp
    spec:
      containers:
      - name: myoctopusapp
        image: ghcr.io/elijahsgh/octopusdemoapppublic:latest
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: octopusdemoservice
  namespace: octopusdemo
  labels:
    app: myoctopusapp
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  selector:
    app: myoctopusapp
  type: LoadBalancer
  loadBalancerIP: ""
