name: Build and push Docker image to GHCR

on:
  push:
    tags:
      - v*

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write # Permission to push to GHCR

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build release
      uses: docker/build-push-action@v6

      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/octopusdemoapp:${{ github.ref_name }}, ghcr.io/${{ github.repository_owner }}/octopusdemoapp:latest
